import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
    faFacebook,
    faTwitter,
    faInstagram,
    faLinkedin,
    faYoutube,
} from "@fortawesome/free-brands-svg-icons";

import Navbar from "@/components/Navbar";

import "./globals.scss";
import "flickity/css/flickity.css";
import { getFooterContent, getNavContent } from "@/data/getData";
import FooterMapper from "@/components/footerTools/FooterMapper";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Test App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const navContent = await getNavContent();
    const footerContent = await getFooterContent();

    const getFooter = () => {
        return footerContent.map(({label, content, id}) => (
            <div key={id} className="menu-slot">
                <h4>{label}</h4>
                {content.map(link => (<span>{link}</span>))}
            </div>
        ))
    }

    return (
        <html lang="en">
            <body className={font.className}>
                <header>
                    <Navbar content={navContent} />
                </header>
                {children}
                <footer>
                    <span className="logo">COMPANY LOGO</span>
                    <div className="footer-menu">
                        {getFooter()}
                    </div>
                    <div className="mobile-menu">
                        <FooterMapper items={footerContent}/>
                    </div>
                    <div className="line" />
                    <div className="footer-glossary">
                        <span>© 2022 Company Inc.</span>
                        <span>Terms and conditions</span>
                        <span>Privacy policy</span>
                        <span>Website by atomix</span>
                        <div className="social-icons">
                            <FontAwesomeIcon
                                icon={faFacebook}
                                className="icon"
                            />
                            <FontAwesomeIcon
                                icon={faTwitter}
                                className="icon"
                            />
                            <FontAwesomeIcon
                                icon={faInstagram}
                                className="icon"
                            />
                            <FontAwesomeIcon
                                icon={faLinkedin}
                                className="icon"
                            />
                            <FontAwesomeIcon
                                icon={faYoutube}
                                className="icon"
                            />
                        </div>
                    </div>
                </footer>
            </body>
        </html>
    );
}
